[dump]
; Just python for now until we scale up
osv_dump_url = https://storage.googleapis.com/osv-vulnerabilities/PyPI/all.zip
archive_path = data/OSV-PyPI-all.zip
force_download = false

; This is all of them
; osv_dump_url = https://storage.googleapis.com/osv-vulnerabilities/all.zip
; archive_path = data/OSV-all.zip

[clone]
osv_dir = data/osv_dump ; TODO we don't extract the zip anymore, so this sin't a directory - need to update this when we get back to git cloning
target_dir = data/repos
max_repos =
update_existing = false

[scores]
jsonl_output = data/osv_recidivism.jsonl
archive_path = data/OSV-PyPI-all.zip
batch_size = 1000
